title: "Miguel Angel Moctezuma Cedillo - Data Scientist & Financial Analyst"
theme: jekyll-theme-cayman
description: "Portafolio Profesional - Ciencia de Datos y Finanzas"
baseurl: ""
url: "https://miguelmoc1.github.io"

