title: "Miguel Angel Moctezuma Cedillo - Data Scientist & Financial Analyst"
theme: minima
description: "Portafolio Profesional - Ciencia de Datos y Finanzas"
baseurl: ""
url: "https://miguelmoc1.github.io"

